# Basic LAMP stack

version: "2.1"

services:
  # Web
  web:
    hostname: web
    image: docksal/web:edge-apache2.4
    volumes:
      # Project root volume
      - project_root:/var/www:ro
      - ${PROJECT_ROOT}/.docksal/etc/apache/host.conf:/usr/local/apache2/conf/extra/includes/host.conf:ro
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_FILE_PROXY
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
    depends_on:
      - cli
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # DB
  db:
    hostname: db
    image: docksal/db:latest
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # CLI
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: docksal/cli:php7
    volumes:
      # Project root volume
      - project_root:/var/www:rw
      # Shared ssh-agent socket
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
      - HOST_UID
      - HOST_GID
      - XDEBUG_ENABLED=1
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=192.168.64.1
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Solr
  solr:
    hostname: solr
    image: docksal/solr:solr3
    ports:
       - "0:8983"
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro

  # VNC to selenium server for behat tests.
  browser:
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
      - "0:5900"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
