<?php

/**
 * Implements hook_block_info().
 */
function front_page_blocks_block_info() {
  // This example comes from node.module.
  /*
   *$blocks['syndicate'] = array(
   *  'info' => t('Syndicate'),
   *  'cache' => DRUPAL_NO_CACHE
   *);
   */
  $blocks['droplet_block'] = array(
    'info' => t('Front Page Droplet Block'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function front_page_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
  /*
   *case 'syndicate':
   *  $block['subject'] = t('Syndicate');
   *  $block['content'] = theme('feed_icon', array('url' => url('rss.xml'), 'title' => t('Syndicate')));
   *  break;
   *
   *case 'recent':
   *  if (user_access('access content')) {
   *    $block['subject'] = t('Recent content');
   *    if ($nodes = node_get_recent(variable_get('node_recent_block_count', 10))) {
   *      $block['content'] = theme('node_recent_block', array(
   *        'nodes' => $nodes,
   *      ));
   *    } else {
   *      $block['content'] = t('No content available.');
   *    }
   *  }
   *  break;
   */
    case 'droplet_block':
      $block['subject'] = t('');
      $block['content'] = droplet_block_content();
      break;

  }
  return $block;
}



function droplet_block_content() {
  $content = '<div id="droplet_wrapper">
    <div id="html5css3" class="droplet"></div>
    <div id="drupalisawesome" class="droplet"></div>
    <div id="theprocess" class="droplet"></div>
    <div id="whywerock" class="droplet"></div>
    <div id="technology" class="droplet"></div>
    <div id="aboutus" class="droplet"></div>
  </div>';

  return $content;
}


