#!/usr/bin/env bash

## Configure solr container to match Dixon's needs.
##
## Usage: fin solr
##
## This is mostly meant to be run during the initial setup.

# Abort if anything fails
set -e

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
ARTIFACT_PATH="${PROJECT_ROOT}/artifacts"

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }


#-------------------------- Functions --------------------------------
disable_patheon_solr()
{
  cd $DOCROOT_PATH
  fin drush dis pantheon_apachesolr -y
}

set_local_solr_environments()
{
  SOLR_PORT=$(docker-compose port solr 8983 2>/dev/null | sed "s/0\.0\.0\.0://")
  fin drush solr-set-env-url http://$VIRTUAL_HOST:$SOLR_PORT/solr --id=solr
}
#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------
echo -e "${green} Disabling the pantheon solr integration${NC}"
disable_patheon_solr

echo -e "${green} Updating solr settings for local development${NC}"
set_local_solr_environments

#-------------------------- END: Execution --------------------------------
